name: CI-build
on: push
jobs:
  ci-job:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 22.x
        check-latest: true
    - run: npm install
    - run: npx tsc  
    - run: node --test --test-reporter=@reporters/github test\* 
    - run: node built\runwf.js .github\workflows\hello-world.yml
    - run: node built\runwf.js .github\workflows\if-statement.yml
            
