name: hello-world
 
on: 
  workflow_call:

env:
  msg: 'Should not be printed'
defaults:
  run:
    shell: bash
jobs:
  cmd-out:
    runs-on: windows-latest
    env:
      msg: 'Should not be printed'
    needs: pwsh-out
    defaults:
      run:
        shell: pwsh
    steps:
      - name: HW-CMD
        env: 
          msg: 'Hello World from CMD'
        run: |
          echo %msg%!
          echo ${{ env.msg }} again
        shell: cmd
  pwsh-out:
    runs-on: windows-latest
    env:
      msg: 'Should not be printed'
    defaults:
      run:
        shell: pwsh
    steps:
      - name: HW-Powershell
        env: 
          msg: 'Hello World from Powershell'
        run: |
          Write-Host "${Env:msg} $($host.version.Major).$($host.version.Minor)!"
          Write-Host "${{ env.msg }} again"
        shell: powershell
      - name: HW-PWSH
        env: 
          msg: 'Hello World from Powershell'
        run: |
          Write-Host "${Env:msg} $($host.version.Major).$($host.version.Minor)!"
          Write-Host "${{ env.msg }} again"
  bash-out:
    runs-on: windows-latest
    env:
      msg: 'Should not be printed'
    needs: [pwsh-out, cmd-out]
    defaults:
      run:
        shell: pwsh
    steps:
      - name: HW-BASH  
        env: 
          msg: 'Hello World from BASH'
        run: |
          echo ${msg}!
          echo ${{ env.msg }} again
        shell: bash
      - name: HW-PYTHON  
        env: 
          msg: 'Hello World from Python'
        run: |
          import os
          print(os.environ["msg"] + "!")
          print("${{ env.msg }} again")
        shell: python