name: hello-world
on: push
env:
  msg: 'Should not be printed'
defaults:
  run:
    shell: bash
jobs:
  my-job:
    runs-on: windows-latest
    env:
      msg: 'Should not be printed'
    defaults:
      run:
        shell: pwsh
    steps:
      - name: HW-CMD
        env: 
          msg: 'Hello World from CMD'
        run: |
          echo %msg%!
          echo ${{ env.msg }} again
        shell: cmd
      - name: HW-PWSH
        env: 
          msg: 'Hello World from Powershell'
        run: |
          Write-Host "${Env:msg} $($host.version.Major).$($host.version.Minor)!"
          Write-Host "${{ env.msg }} again"
        shell: powershell
      - name: HW-PWSH
        env: 
          msg: 'Hello World from Powershell'
        run: |
          Write-Host "${Env:msg} $($host.version.Major).$($host.version.Minor)!"
          Write-Host "${{ env.msg }} again"
      - name: HW-BASH
        env: 
          msg: 'Hello World from BASH'
        run: |
          echo ${msg}!
          echo ${{ env.msg }} again
        shell: bash