name: if-statement
on: push
env:
  test: true
jobs:
  test-steps:
    runs-on: windows-latest
    steps:
      - name: Step should show
        if: ${{ env.test }}
        run: Write-Host "This text should show!"
      - name: Step should not show
        if: ${{ !(env.test) }}
        run: Write-Host "This text should not show!"
  test-jobs-show:
    runs-on: windows-latest
    if: env.CI
    steps:
      - name: Job should show
        run: Write-Host "This text should show!"
  test-jobs-no-show:
    if: ${{ !(env.CI) }}
    runs-on: windows-latest
    steps:
      - name: Job should not show
        run: Write-Host "This text not should show!"
