name: using-example
on: push
jobs:
  my-job:
    runs-on: windows-latest
    steps:
      - name: Print to Log
        id: print-to-log
        uses: actions/hello-world-javascript-action@main
        with:
          who-to-greet: "nobody"
      - name: Same repo
        uses: ./.github/actions/hello-world